import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Next App Example',
    description: 'Generated by create next app',
};

const routes = [
    {id: 1, href: '/', name: 'Home'},
    {id: 2, href: 'courses', name: 'Courses'},
    {id: 3, href: '/children', name: 'For Children'},
    {id: 4, href: '/about', name: 'About Us'},
    {id: 4, href: '/items', name: 'Items'},
]

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <nav>
            <ul className="border border-black p-4 flex justify-between">
                <div className="flex gap-2">
                    {routes.map(({id, name, href}) => {
                        return (
                            <Link href={href} key={id}>
                                <li className="p-2 border rounded-lg hover:cursor-pointer">
                                    {name}
                                </li>
                            </Link>
                        )
                    })}
                </div>

                <Link href="/login">
                    <li className="p-2 border rounded-lg hover:cursor-pointer">
                        Login
                    </li>
                </Link>
            </ul>
        </nav>
        {children}
        </body>
        </html>
    );
}
